### ISSUE TITLE
Can't add image to gallery (NoMethodError in Refinery::Portfolio::Admin::ItemsController#new)

### ISSUE THREAD

**Issue by clevertechru** [refinery/refinerycms-portfolio#85] opened 2012-12-21 15:53 UTC
refinerycms 2.0.9, portfolio 2.0-stable
on list of galleries (/refinery/portfolio/galleries) click on "add image" in list:

NoMethodError in Refinery::Portfolio::Admin::ItemsController#new
undefined method `to_i' for #<Refinery::Portfolio::Gallery:0x7f176f4c2088>

on 
![Screenshot from 2012-12-21 19:32:39-refinery-crop](https://f.cloud.github.com/assets/1336340/27392/79400662-4b86-11e2-8cde-754e555006d1.png)
/refinery/portfolio/galleries/--3/items/new

**Comment by bricesanchez** [comment] 2015-08-13 03:23
The issue is outdated, i'm closing it.

**Closed by bricesanchez** 2015-08-13 03:23 UTC
