### ISSUE TITLE
"No items yet" translation missing for admin top-level images list

### ISSUE THREAD

**Issue by gwagener** [refinery/refinerycms-portfolio#79] opened 2012-11-18 22:53 UTC
If no top level images have been added, viewing the list displays "i18n: No Items Yet".  The translations files are missing refinery.admin.items.index.no_items_yet.  Also, I think there are some unused translations lying around in there.  Possibly some file structures changed and the translation paths weren't updated.

**Comment by bricesanchez** [comment] 2015-08-13 03:22
The issue is outdated, i'm closing it.

**Closed by bricesanchez** 2015-08-13 03:22 UTC
