### ISSUE TITLE
Can't add image to gallery by clicking the "Add an image to this gallery" button

### ISSUE THREAD

**Issue by jerefrer** [refinery/refinerycms-portfolio#76] opened 2012-11-12 09:24 UTC
Hi there,

When I click the "Add an image to this gallery" next to a gallery in the admin galleries#index page I'm redirected to the new image form but with no gallery selected in the dropdown menu. Also the gallery I created could not be selected in that dropdown menu.

If I click create the image will then be properly created, but as a *top-level* image, not inside the gallery I wanted.

Creating images through the "Add an image button" on galleries#index works perfectly though, provided I selected the proper gallery in the dropdown menu (and this time the gallery I created was selectable)

Cheers !

**Comment by bricesanchez** [comment] 2015-08-13 03:22
The issue is outdated, i'm closing it.

**Closed by bricesanchez** 2015-08-13 03:22 UTC
