### ISSUE TITLE
Image and "there is no image" both displayed when editing an image

### ISSUE THREAD

**Issue by gwagener** [refinery/refinerycms-portfolio#78] opened 2012-11-18 22:49 UTC
In 2-0-stable, when you edit an image it displays the image followed by the message "There is currently no image selected, please click here to add one." followed by the link to remove the image.

Steps to reproduce:
- create a gallery
- add an image to it via the "Add an image" action
- view the gallery's images via the "X images" link
- click the "Edit this image" button

**Comment by bricesanchez** [comment] 2015-08-13 03:22
The issue is outdated, i'm closing it.

**Closed by bricesanchez** 2015-08-13 03:22 UTC
