### ISSUE TITLE
fail generate portfolio css for customize in 2.0-stable

### ISSUE THREAD

**Issue by clevertechru** [refinery/refinerycms-portfolio#84] opened 2012-12-02 11:22 UTC
# rake refinery:override stylesheet=portfolio
Error: Couldn't match any stylesheet files in any extensions like portfolio

2.0-stable

**Comment by bricesanchez** [comment] 2015-08-13 03:21
The issue is outdated, i'm closing it.

**Closed by bricesanchez** 2015-08-13 03:21 UTC
