### ISSUE TITLE
Bundle install failed

### ISSUE THREAD

**Issue by talhait07** [refinery/refinerycms-portfolio#93] opened 2013-09-03 09:16 UTC
I am getting the following error while bundle installing the gem 
Resolving dependencies...

Bundler could not find compatible versions for gem "refinerycms-core":
  In snapshot (Gemfile.lock):
    refinerycms-core (2.1.0)

In my gemfile i added the following line 
gem 'refinerycms-portfolio', :git => 'git://github.com/refinery/refinerycms-portfolio.git', branch: 'master'

Please help me to get out of this issue.

**Comment by viecode09** [comment] 2015-01-20 19:17
Yes I do have the same issue, But for temporary solution I forked this project to my own repo, then I point the refinery path to my repo.. it works temporarily..

Thanks

**Comment by bricesanchez** [comment] 2015-08-13 03:23
The issue is outdated, i'm closing it.

**Closed by bricesanchez** 2015-08-13 03:23 UTC
